#!/usr/bin/env node
/**
 * Install RepoPlanner API routes into a Next.js app so the host doesn't own planning logic.
 * Run from repo root: node vendor/repo-planner/scripts/install-routes.mjs [--app-dir=docs-site] [--dry-run]
 *
 * Writes thin re-export route files under app-dir/app/api/ that delegate to the package.
 * Uses relative path from each route file to vendor/repo-planner/api/.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = path.resolve(__dirname, "..");
const API_DIR = path.join(PACKAGE_ROOT, "api");

/** Routes the package provides: path segment under app/api/ -> path under package api/ */
const ROUTES = [
  ["test-reports/unit", "test-reports/unit", ["GET"]],
  ["planning-state", "planning-state", ["GET"]],
  ["planning-cli/run", "planning-cli/run", ["POST"]],
  ["planning-reports/latest", "planning-reports/latest", ["GET"]],
  ["planning-metrics", "planning-metrics", ["GET"]],
  ["planning-edits/apply", "planning-edits/apply", ["POST"]],
];

function parseArgs() {
  const args = process.argv.slice(2);
  let appDir = "docs-site";
  let dryRun = false;
  for (const a of args) {
    if (a === "--dry-run") dryRun = true;
    else if (a.startsWith("--app-dir=")) appDir = a.slice("--app-dir=".length);
    else if (a === "--help" || a === "-h") {
      console.log(`
install-routes.mjs [--app-dir=docs-site] [--dry-run]

  Installs RepoPlanner API routes into the Next.js app at --app-dir.
  Each installed file re-exports GET/POST from the package so the host does not own planning logic.

  --app-dir   Next.js app directory (default: docs-site)
  --dry-run   Print what would be written, do not write
`);
      process.exit(0);
    }
  }
  return { appDir, dryRun };
}

function relativeFromTo(fromDir, toDir) {
  const from = path.resolve(fromDir);
  const to = path.resolve(toDir);
  const rel = path.relative(from, to);
  return rel.replace(/\\/g, "/");
}

async function main() {
  const { appDir, dryRun } = parseArgs();
  const appRoot = path.resolve(process.cwd(), appDir);
  const appApi = path.join(appRoot, "app", "api");

  const packageApiRel = relativeFromTo(appApi, path.join(PACKAGE_ROOT, "api"));
  const prefix = packageApiRel.startsWith("..") ? packageApiRel : `./${packageApiRel}`;

  for (const [routePath, packagePath, exports] of ROUTES) {
    const routeDir = path.join(appApi, routePath);
    const routeFile = path.join(routeDir, "route.ts");
    const segments = routePath.split("/").length;
    const back = "../".repeat(segments + 3);
    const importPath = `${back}${path.join("vendor", "repo-planner", "api", packagePath).replace(/\\/g, "/")}/route`;
    const exportList = exports.join(", ");
    const content = `/** Generated by RepoPlanner install-routes. Do not edit; re-run to update. */\n\nexport { ${exportList} } from "${importPath}";\n`;

    if (dryRun) {
      console.log(`[dry-run] ${routeFile}\n${content}`);
      continue;
    }
    await fs.mkdir(routeDir, { recursive: true });
    await fs.writeFile(routeFile, content, "utf-8");
    console.log(`Wrote ${routeFile}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
